1261153 - Added disk/ram/cpu validations to fusor-undercloud-installer. (#43)

diff --git a/bin/fusor-undercloud-installer b/bin/fusor-undercloud-installer
--- a/bin/fusor-undercloud-installer
+++ b/bin/fusor-undercloud-installer
@@ -2,22 +2,34 @@
 
 fusor_undercloud_install() {
 
-  interactive=true
-  # Check if we are in non-interactive mode
-  if [ "$#" -eq 1 ]; then
-    case $1 in
-      --non-interactive)
-      CONF_FILE='/etc/fusor-undercloud-installer/fusor-undercloud-installer.answers.yaml'
-      interactive=false
-      ;;
-      --answer-file=*)
-      CONF_FILE="${1#*=}"
-      interactive=false
-      ;;
-      *)
-      echo 'Invalid argument... staying in interactive mode'
-    esac
+  if [ "$(id -u)" != "0" ]; then
+   echo "This script must be run as root"
+   exit 1
   fi
+
+  interactive=true
+  skip_system_validations=false
+  # Check if we are in non-interactive mode
+  # Check if validations on system requirements should be skipped.
+  while test $# -gt 0
+  do
+    case "$1" in
+      --non-interactive)
+        CONF_FILE='/etc/fusor-undercloud-installer/fusor-undercloud-installer.answers.yaml'
+        interactive=false
+        ;;
+      --answer-file=*)
+        CONF_FILE="${1#*=}"
+        interactive=false
+        ;;
+      --skip-validations)
+        skip_system_validations=true
+        ;;
+      *) echo 'Invalid argument... staying in interactive mode'
+        ;;
+    esac
+    shift
+  done
 
   # Check if configuration file exists
   if [ $interactive == false ]; then
@@ -29,6 +41,18 @@ fusor_undercloud_install() {
     fi
   fi
   export CONF_FILE
+
+  # Check if --skip-validations option was supplied
+  if [ $skip_system_validations == false ]; then
+    echo
+    # 8 cores required, 8 recommended
+    check_cpu_cores 8 8
+    # 16 gb ram required, 16 gb recommended
+    check_ram 16 16
+    # 40 gb disk space at '/' required, 100 gb recommended
+    check_disk_space 40 100 "/"
+    echo
+  fi
 
   # create stack user, become her
   id -u stack >/dev/null 2>&1
@@ -201,6 +225,124 @@ enabled=1" > /etc/yum.repos.d/fake.repo
   echo "Your IP Address is:"
   python -c "import netifaces as ni; print ni.ifaddresses('br-ctlplane')[2][0]['addr']"
   echo "Make a note of this for the RHCI web UI."
+}
+
+check_cpu_cores() {
+  # Check if machine has enough CPU cores
+  cores_required=$1
+  cores_recommended=$2
+
+  intro_message="Checking CPU cores..."
+  cores_found=$(nproc)
+
+  # condition: CPU core count recommendation met
+  if [ $cores_found -ge $cores_recommended ]; then
+    print_with_outcome "$intro_message" "$cores_found cores" true
+  # condition: CPU core count minimum requirement met
+  elif [ $cores_found -ge $cores_required ]; then
+    print_with_outcome "$intro_message" "$cores_found cores" true
+    echo $cores_required cores required, $cores_recommended recommended.
+  # condition: CPU core count insufficient
+  else
+    print_with_outcome "$intro_message" "$cores_found cores" false
+    echo $cores_required cores required, $cores_recommended recommended.
+    if [ "$interactive" == true ]; then
+      read -p "Proceed without meeting CPU core requirement? (y/n) " -r
+    else
+      REPLY="n"
+    fi
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+      echo && echo "To skip system validations, run fusor-undercloud-installer with '--skip_validations'."
+      echo Exiting...
+      echo && exit 1
+    fi
+  fi
+}
+
+check_ram() {
+  # System memory check
+  gb_ram_required=$1    # required system memory in gigabytes
+  gb_ram_recommended=$2 # recommended system memory in gigabytes
+
+  let mb_ram_required=gb_ram_required*1024
+  let mb_ram_recommended=gb_ram_recommended*1024
+
+  intro_message="Checking RAM size..."
+
+  # dmidecode -t 17 gives a listing of installed RAM modules
+  mb_ram_found=0
+  for i in $( sudo dmidecode -t 17 | awk '/Size:/ {print $2}' ); do
+    let mb_ram_found=mb_ram_found+i
+  done
+
+  # condition: RAM recommendation met
+  if [ $mb_ram_found -ge $mb_ram_recommended ]; then
+    print_with_outcome "$intro_message" "$mb_ram_found MB" true
+  # condition: RAM minimum requirement met
+  elif [ $mb_ram_found -ge $mb_ram_required ]; then
+    print_with_outcome "$intro_message" "$mb_ram_found MB" true
+    echo $mb_ram_required MB RAM required, $mb_ram_recommended MB recommended.
+  # condition: RAM insufficient
+  else
+    print_with_outcome "$intro_message" "$mb_ram_found MB" false
+    echo $mb_ram_required MB RAM required, $mb_ram_recommended MB recommended.
+    if [ "$interactive" == true ]; then
+      read -p "Proceed without meeting RAM requirement? (y/n) " -r
+    else
+      REPLY="n"
+    fi
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+      echo && echo "To skip system validations, run fusor-undercloud-installer with '--skip_validations'."
+      echo Exiting...
+      echo && exit 1
+    fi
+  fi
+}
+
+check_disk_space() {
+  # Verify disk space available at directory_to_check
+  disk_space_required=$1     # required disk space in gigabytes
+  disk_space_recommended=$2  # recommended disk space in gigabytes
+  directory_to_check=$3      # directory to check for disk space
+
+  intro_message="Checking '$directory_to_check'..."
+  root_size_gb=$(df -BG $3 | awk '/\// {print $2}' | egrep -o '[0-9]+')
+
+  # condition: Disk size recommendation met
+  if [ $root_size_gb -ge $disk_space_recommended ]; then
+    print_with_outcome "$intro_message" "$root_size_gb GB" true
+  # condition: Disk size minimum requirement met
+  elif [ $root_size_gb -ge $disk_space_required ]; then
+    print_with_outcome "$intro_message" "$root_size_gb GB" true
+    echo $disk_space_required GB disk space required, $disk_space_recommended GB recommended.
+  # condition: Disk size insufficient
+  else
+    print_with_outcome "$intro_message" "$root_size_gb GB" false
+    echo $disk_space_required GB disk space required, $disk_space_recommended GB recommended.
+    if [ "$interactive" == true ]; then
+      read -p "Proceed without meeting disk space requirement? (y/n) " -r
+    else
+      REPLY="n"
+    fi
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+      echo && echo "To skip system validations, run fusor-undercloud-installer with '--skip_validations'."
+      echo Exiting...
+      echo && exit 1
+    fi
+  fi
+}
+
+print_with_outcome() {
+  # Print a status message with OK or FAILED
+  outcome_message=$1  # message to print
+  outcome_amount=$2   # amount of resource found
+  outcome_status=$3   # true = OK, false = FAILED
+
+  if [ "$outcome_status" = true ] ; then
+    printf "%-23s %-10s \e[32m%-5s\e[0m\n" "$outcome_message" "$outcome_amount" "[  OK  ]"
+  else
+    printf "%-23s %-10s \e[91m%-5s\e[0m\n" "$outcome_message" "$outcome_amount" "[FAILED]"
+  fi
 }
 
 fusor_undercloud_install "$@" 2>&1 | tee /var/log/fusor-undercloud-install.log
